name: Deploy site100bookartshop

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |
            cd /var/www/u1538455/data/www/bookartshop.ru/wp-content/themes/site100bookartshop
            git clone git@github.com:site100ru/site100bookartshop.git .
            
            #cd /var/www/u1538455/data/www/bookartshop.ru/wp-content/themes/site100bookartshop
            #git pull
